# Generated by Django 4.0.4 on 2022-04-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_slider_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
