# Generated by Django 4.0.4 on 2022-05-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_cart_items_alter_cart_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
